<a href="https://colab.research.google.com/github/satyhim/Projects/blob/main/Seeds_Data_Classi_Algorithm3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Seeds Data Project : Classification Algorithm 

In [43]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [44]:
Seeds_Data= pd.read_excel('/content/drive/MyDrive/Python/Project/seeds_dataset.xlsx')

In [45]:
Seeds_Data.head()

Area  Perimeter  Compactness  Length of Kernel  Width of Kernel  \
0  15.26      14.84       0.8710             5.763            3.312   
1  14.88      14.57       0.8811             5.554            3.333   
2  14.29      14.09       0.9050             5.291            3.337   
3  13.84      13.94       0.8955             5.324            3.379   
4  16.14      14.99       0.9034             5.658            3.562   

   Asymmetry coefficient  Length of kernel groove  Class (1_2_3  
0                  2.221                    5.220             1  
1                  1.018                    4.956             1  
2                  2.699                    4.825             1  
3                  2.259                    4.805             1  
4                  1.355                    5.175             1

In [46]:
Seeds_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Area                     210 non-null    float64
 1   Perimeter                210 non-null    float64
 2   Compactness              210 non-null    float64
 3   Length of Kernel         210 non-null    float64
 4   Width of Kernel          210 non-null    float64
 5   Asymmetry coefficient    210 non-null    float64
 6   Length of kernel groove  210 non-null    float64
 7   Class (1_2_3             210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [47]:
Seeds_Data.describe()

Area   Perimeter  Compactness  Length of Kernel  Width of Kernel  \
count  210.000000  210.000000   210.000000        210.000000       210.000000   
mean    14.847524   14.559286     0.870999          5.628533         3.258605   
std      2.909699    1.305959     0.023629          0.443063         0.377714   
min     10.590000   12.410000     0.808100          4.899000         2.630000   
25%     12.270000   13.450000     0.856900          5.262250         2.944000   
50%     14.355000   14.320000     0.873450          5.523500         3.237000   
75%     17.305000   15.715000     0.887775          5.979750         3.561750   
max     21.180000   17.250000     0.918300          6.675000         4.033000   

       Asymmetry coefficient  Length of kernel groove  Class (1_2_3  
count             210.000000               210.000000    210.000000  
mean                3.700201                 5.408071      2.000000  
std                 1.503557                 0.491480      0.818448  
min                 0.765100                 4.519000      1.000000  
25%                 2.561500                 5.045000      1.000000  
50%                 3.599000                 5.223000      2.000000  
75%                 4.768750                 5.877000      3.000000  
max                 8.456000                 6.550000      3.000000

In [48]:
Seeds_Data.isna().sum()

Area                       0
Perimeter                  0
Compactness                0
Length of Kernel           0
Width of Kernel            0
Asymmetry coefficient      0
Length of kernel groove    0
Class (1_2_3               0
dtype: int64

In [49]:
X = Seeds_Data.drop(['Class (1_2_3'], axis=1)

y = Seeds_Data['Class (1_2_3']

In [50]:
# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report


# Function to split the dataset
def splitdataset(Seeds_Data):

	# Separating the target variable
	X = Seeds_Data.drop(['Class (1_2_3'], axis=1)
	Y = Seeds_Data['Class (1_2_3']

	# Splitting the dataset into train and test
	X_train, X_test, y_train, y_test = train_test_split(
	X, Y, test_size = 0.3, random_state = 100)
	
	return X, Y, X_train, X_test, y_train, y_test
	
# Function to perform training with giniIndex.
def train_using_gini(X_train, X_test, y_train):

	# Creating the classifier object
	clf_gini = DecisionTreeClassifier(criterion = "gini",
			random_state = 100,max_depth=3, min_samples_leaf=5)

	# Performing training
	clf_gini.fit(X_train, y_train)
	return clf_gini
	
# Function to perform training with entropy.
def tarin_using_entropy(X_train, X_test, y_train):

	# Decision tree with entropy
	clf_entropy = DecisionTreeClassifier(
			criterion = "entropy", random_state = 100,
			max_depth = 3, min_samples_leaf = 5)

	# Performing training
	clf_entropy.fit(X_train, y_train)
	return clf_entropy


# Function to make predictions
def prediction(X_test, clf_object):

	# Predicton on test with giniIndex
	y_pred = clf_object.predict(X_test)
	print("Predicted values:")
	print(y_pred)
	return y_pred
	
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
	
	print("Confusion Matrix: ",
		confusion_matrix(y_test, y_pred))
	
	print ("Accuracy : ",
	accuracy_score(y_test,y_pred)*100)
	
	print("Report : ",
	classification_report(y_test, y_pred))

# Driver code
def main():
	
	# Building Phase
	data = Seeds_Data
	X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
	clf_gini = train_using_gini(X_train, X_test, y_train)
	clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
	
	# Operational Phase
	print("Results Using Gini Index:")
	
	# Prediction using gini
	y_pred_gini = prediction(X_test, clf_gini)
	cal_accuracy(y_test, y_pred_gini)
	
	print("Results Using Entropy:")
	# Prediction using entropy
	y_pred_entropy = prediction(X_test, clf_entropy)
	cal_accuracy(y_test, y_pred_entropy)
	
	
# Calling main function
if __name__=="__main__":
	main()

Results Using Gini Index:
Predicted values:
[1 3 1 3 2 1 3 2 3 3 2 2 2 1 2 1 1 2 1 3 2 2 2 2 3 1 2 1 1 1 3 1 3 3 2 3 3
 3 3 2 2 1 2 2 1 3 3 1 3 2 1 3 3 3 1 3 3 1 1 2 1 2 2]
Confusion Matrix:  [[15  0  1]
 [ 0 21  0]
 [ 5  0 21]]
Accuracy :  90.47619047619048
Report :                precision    recall  f1-score   support

           1       0.75      0.94      0.83        16
           2       1.00      1.00      1.00        21
           3       0.95      0.81      0.88        26

    accuracy                           0.90        63
   macro avg       0.90      0.92      0.90        63
weighted avg       0.92      0.90      0.91        63

Results Using Entropy:
Predicted values:
[3 3 3 3 2 3 3 2 3 3 2 2 2 3 2 1 3 2 3 3 2 2 2 2 3 3 2 3 1 1 3 1 3 3 2 3 3
 3 3 2 2 1 2 2 1 3 3 3 3 2 1 3 3 3 1 3 3 1 3 2 3 2 2]
Confusion Matrix:  [[ 9  0  7]
 [ 0 21  0]
 [ 0  0 26]]
Accuracy :  88.88888888888889
Report :                precision    recall  f1-score   support

           1       1.00      